### ISSUE TITLE
Bot not following commands

### ISSUE THREAD

**Issue by greatinternetmachine** [kolbytn/mindcraft#71] opened 2024-05-02 03:30 UTC
Minecraft version: Minecraft 1.20.4
AI model: llama3 

It's in the title - not many other details I can provide. Console registers that I've said something in chat, however, the bot itself will not do anything. "Follow me", or any simple commands do not process at all. It joins the game and does its own thing.

**Comment by Luca-Girotti** [comment] 2024-05-08 10:39
I have the same issue, it seems that with llama3 the bot doesn't take any input from the user!

**Comment by BorbTheBird** [comment] 2024-05-09 06:53
yeah it would be nice if they had more documentation on using llama3 I have no idea how to use it with these bots

**Comment by AuXFire** [comment] 2024-05-11 16:49
If you are using the small Llama3 (8B) it will be quite difficult to get it to work as intended. It just does not have enough training to handle the complexity. Try with the 70B model. Even then, most of the issue lies in the prompting and not using function calling when needed.

**Comment by Luca-Girotti** [comment] 2024-05-12 12:36
Not quite sure if changing the model, will indeed solve the issue, plus i wouldn't how to set another model to be honest.

**Comment by kolbytn** [comment] 2024-05-13 19:42
My experiments with llama3 8b have resulted in mostly poor behavior. It fails to work on the any but the simplest commands. If the model is taking a long time, it may be because your computer hardware is not capable of running it. We included support for local models since it was a highly requested feature, but most local models will not perform as well as larger models.

I'm closing this issue as it seems to be an issue with the choice of model / the hardware you're running it on.

**Closed by kolbytn** 2024-05-13 19:42 UTC
