### ISSUE TITLE
The bot gets stuck in blocks and goes back and forth if you help him.

### ISSUE THREAD

**Issue by Zapzatron** [kolbytn/mindcraft#70] opened 2024-05-01 19:46 UTC
The bot has connected to the server and has just been standing there for a long time.
![andy_npc_is_doing_nothing](https://github.com/kolbytn/mindcraft/assets/100136305/391b1679-f658-442d-ae3d-1c990732480d)
But he has running effects near his feet.
![image](https://github.com/kolbytn/mindcraft/assets/100136305/14ddf6c9-621b-44d4-873a-471efc025614)
Broke the block next to him, now he's running back and forth.

https://github.com/kolbytn/mindcraft/assets/100136305/91077efc-912a-4f98-9d0b-a76d65436513

**Comment by kolbytn** [comment] 2024-05-13 19:37
The andynpc profile is experimental. I'm closing this issue for now since it does not seem to be reproducible or identify a specific bug.

**Closed by kolbytn** 2024-05-13 19:37 UTC
