### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by Zapzatron** [kolbytn/mindcraft#76] opened 2024-05-08 15:14 UTC
![image](https://github.com/kolbytn/mindcraft/assets/100136305/fa5faa3f-ffe9-4a62-afeb-d575204bda5f)
Endlessly restarts with this error and each restart resends requests to the API again

**Comment by kolbytn** [comment] 2024-05-13 19:48
Thanks for pointing this out. I can't be sure since I am unable to reproduce the issue, but it's probably an issue with [this function](https://github.com/kolbytn/mindcraft/blob/1c75f4f688ae3837e6eaf8a08989e58967b01fd3/src/agent/library/world.js#L36) not finding a spot to place the building in. Marking this as a bug TODO.

**Comment by kolbytn** [comment] 2024-08-23 23:36
Closing since we've fixed more bugs, let me know if the issue persists.

**Closed by kolbytn** 2024-08-23 23:36 UTC
Labels: bug
